version: "3.3"

services:
  mqtt:
    container_name: "mqtt"
    image: eclipse-mosquitto:2
    user: root
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/conf:/mosquitto/config
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data
    restart: unless-stopped
  
  mqtt-explorer:
    container_name: "mqtt-explorer"
    image: smeagolworms4/mqtt-explorer
    user: root
    ports:
      - 4000:4000
    volumes:
      - ./mqtt-explorer/config:/mqtt-explorer/config
    environment:
      - HTTP_PORT=4000
      - CONFIG_PATH=/mqtt-explorer/config
    restart: unless-stopped
